### ISSUE TITLE
Agree on naming convention for code

### ISSUE THREAD

**Issue by jonesg2** [jonesg2/TeamZeusProject#2]
Need to agree on a naming convention for code to make sharing code more user friendly.

**Comment by jonesg2** [comment]
1st 2 letters, data type/function data set name. abbreviated to 1st letter capitalized.
separator _ 

e.g.
DF_LCD_REGIONS

@AlexLRose @CharlotteOB @jaysheppard 

 please can you confirm if in agreement? if il make amendments to the codes uploaded

**Comment by jaysheppard** [comment]
I totally agree with this naming convention. 

Always efficient to have the start of an object/variable name to display what it is; DF being data frame, AG being an aggregate, and so on. Makes it easier for other members to understand the code and what you're doing. 

I'm happy to go with this style of naming convention. Everyone else in agreement?

**Comment by ghost** [comment]
I agree 100% with this naming convention. Makes it so much easier to see what is going on and to understand other peoples work.

Love it!

**Comment by jonesg2** [comment]
I have spoken with @AlexLRose  Who is agreement also.

I'l go through and amend the code to the new naming convention  but i probably wont have time to do it this week.

I'l close off the issue once done.

**Comment by jonesg2** [comment]
I've updated the naming convention on the code script for forecasting
