### ISSUE TITLE
Stages of Lung Cancer Research

### ISSUE THREAD

**Issue by jonesg2** [jonesg2/TeamZeusProject#3]
Investigate stages and how this an impact on Lung cancer deaths.

-  How severe lung cancer deaths are to others?

- exploring the data.  How many cases would need to be moved down a stage at diagnosis to reduce the number of deaths?

**Comment by jaysheppard** [comment]
Completed analysis of "how severe lung cancer deaths are to others" >> https://github.com/jonesg2/TeamZeusProject/tree/master/CancerSurvival_Stages

**Comment by jonesg2** [comment]
docs in shared folder.  closing this issue
